// <autogenerated>
//   This file was generated by T4 code generator Amoeba-Master.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using SystemInterfaces;
using Core.Common.UI;
using Interfaces;
using ViewModel.Interfaces;

namespace ViewModels
{
    //[Export(typeof(IEntityCacheViewModel<>))]
    //public class EntityCacheViewModel<TEntity> : ObservableListViewModel<TEntity>, IEntityCacheViewModel<TEntity> where TEntity : IEntity
    //{
    //    public EntityCacheViewModel() { }
       
    //    public EntityCacheViewModel(ISystemProcess process, List<IViewModelEventSubscription<IViewModel, IEvent>> eventSubscriptions, List<IViewModelEventPublication<IViewModel, IEvent>> eventPublications, List<IViewModelEventCommand<IViewModel, IEvent>> commandInfo, Type orientation) : base(eventSubscriptions, eventPublications, commandInfo, process, orientation)
    //    {
    //        this.WireEvents();
    //    }


    //}

   

}
