// <autogenerated>
//   This file was generated by T4 code generator Amoeba-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace EF.Entities
{
	public partial class DataTypes: BaseEntity, IDataTypes
	{
		public virtual string Name { get; set; }
		public virtual string DBType { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<DataProperties> DataProperties {get; set;}
				public virtual ICollection<FunctionReturnType> FunctionReturnType {get; set;}
				public virtual ICollection<Parameters> Parameters {get; set;}
		
			// ---------Parent Relationships
	

	}
}
